config/routes.rb
Delivery::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }
  resources :users do 
    collection do 
      get :validate_your_data
      post :validate_mobile_phone
      post :send_sms
      post :validate_id_image
    end
  end
  match '/delivery' => 'delivery#zone', :via => [:get, :post]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  #attr_accessible :provider, :uid, :name
  validates :mobile_phone, :numericality => { :only_integer => true, :greater_than => 100000 }, :if => :validate_mobile_phone
  validates :last_name, :presence => true, :on => :create

  # FIX-ME we could use state machine
  VALIDATION_STATUS = { '0' => 'none', '1' => 'basic', '2' => 'advanced', '3' => 'maximum'  }

  has_attached_file :id_scan

  after_save :set_validation_status

  def validate_mobile_phone!
    @validate_mobile_phone = true
  end

  def validate_mobile_phone
    @validate_mobile_phone
  end

  def set_validation_status
    if self.confirmed? and validation_status == 0
      update_attribute :validation_status , 1
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    logger.info auth.inspect
    if user
      user.name = (auth.extra.raw_info.first_name rescue nil)
      user.last_name = (auth.extra.raw_info.last_name rescue nil)
      user.email = auth.info.email
      user.birth_date = (auth.extra.raw_info.birthday rescue nil)
      user.mobile_phone = nil
      user.facebook_photo_url = auth.info.image
      user.address = (auth.extra.raw_info.location.name rescue nil) 
      user.save
    else
      user = User.new(name: (auth.extra.raw_info.first_name rescue nil),
        last_name: (auth.extra.raw_info.last_name rescue nil),
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email,
        birth_date: (auth.extra.raw_info.birthday rescue nil),
        mobile_phone: nil,
        facebook_photo_url: auth.info.image,
        address: (auth.extra.raw_info.location.name rescue nil),
        password: Devise.friendly_token[0,20])
      user.skip_confirmation!
      user.save
    end
    if not user.mobile_phone.nil? and user.validation_status < 2
      user.update_attribute :validation_status, 2
    end
    user
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

  protected

  def set_locale
    I18n.locale = params[:locale] if params[:locale]
  end


end

app/controllers/delivery_controller.rb
class DeliveryController < ApplicationController
  def zone
    if request.post?
    else
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_filter :authenticate_user!, except: [ :index, :videos ]
  def index
    @user = current_user
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :last_name)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = current_user
  end

  def validate_your_data
  end

  def send_sms
    user = User.find current_user.id
    user.validate_mobile_phone!
    user.mobile_phone = params.require(:user).permit(:mobile_phone)[:mobile_phone]
    if user.valid?
      user.mobile_phone_code = SecureRandom.hex(5)[0..4]
      user.save
      flash.now[:notice] = "SMS enviado"
    else
      flash.now[:error] = user.errors.messages.to_s
    end
    current_user.reload
    render :validate_your_data
  end

  def validate_mobile_phone
    user = User.find current_user.id
    if params[:mobile_phone_code_received] == user.mobile_phone_code
      user.mobile_phone_code = nil
      user.validation_status = 2
      user.save
      flash.now[:notice] = "Felicitaciones, haz validado tu número de teléfono correctamente."
    else
      flash.now[:error] = "El código de verificación no corresponde"
    end
    current_user.reload
    render :validate_your_data
  end
  
  def validate_id_image
    user = User.find current_user.id
    if user.update_attributes params.require(:user).permit(:id_scan)
      flash[:notice] = "La imagen se subió correctamente. Una vez confirmado tu ID habrás recibido la validación máxima."
    else
      flash[:error] = "Hubo un error al subir la imagen"
    end
    current_user.reload
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/delivery/zone.html.erb
<script type="text/javascript">
  var barrios = [];
  var barrios_layer;
  jQuery(document).ready(function($) {
    $('#save_data').click(function(){
      alert('A modo de prueba se muestra el listado de barrios seleccionados para delivery: '+barrios);
    });
    
    $('#mapa').css('width', $('body').width()-240).css('height', 500);
    
    var clickHandler = function (e, popup) {
      if (e && e.feature) {
        if (barrios.indexOf(e.feature.data.Nombre) == -1) {
          barrios.push(e.feature.data.Nombre);
          barrios_layer.addFeatures([e.feature.clone()]);
        } else {
          barrios.pop(e.feature.data.Nombre);
          barrios_layer.removeFeatures([e.feature.clone()]);
        }
        $('#barrios').text(barrios);
      }
    };
  
    var mapa = new usig.MapaInteractivo('mapa', {
      includeToolbar: false,
      includePanZoomBar: true,
      onReady: function() {
        barrios_layer = mapa.addVectorLayer('Accepted Delivery', { });

        var layer = mapa.addVectorLayer('Barrios', {
            format: 'geojson',
            url: "http://epok.buenosaires.gob.ar/getGeoLayer/?categoria=barrios&formato=geojson",
            disableClick: false,
            minScale: 150000,
            symbolizer: {
              fill: false,
              fillColor: "ee9900",
              fillOpacity: 0.1,
              strokeColor: "#999",
              strokeWidth: 2,
              strokeDashstyle: 'dashdot',
            },
            selectStyle: {
              fillOpacity: 0.5,
              fontColor: "#fff",
              fontSize: "12px",
              strokeWidth: 2
            },
        escalas: [
          {
            minScaleDenominator: 100000,
            maxScaleDenominator: 150000,
            symbolizer: {
              fill: true
            }
          },
          {
            minScaleDenominator: 60000,
            maxScaleDenominator: 100000,
            symbolizer: {
              fill: true,
              label: "${Nombre}",
              fontWeight: "bold",
              fontSize: "24px",
              fontColor: "#555"
            }
          },
          {
            maxScaleDenominator: 60000,
            symbolizer: {
              fill: false,
              label: "${Nombre}",
              fontSize: "20px",
              fontColor: "#555"
            }
          }
        ],
        minPointRadius: 2,
        popup: false,
        onClick: clickHandler
      });
    }
  });      
}); 

</script>

<h1><%= t('text.delivery_zone') %></h1>
<div class="row">
  <div class="col-lg-2">
    <p><span class="label label-info">Zona donde se hace delivery</span>
    <span class="label label-warning">Zona donde no se hace delivery</span></p>
  </div>
  <div class="col-lg-2">
    <%= link_to t('buttons.save'), '#', id: 'save_data', class: 'btn btn-default' %>
  </div>
  <div class="col-lg-5">
    <p>Seleccioná las áreas donde querés hacer delivery</p>
    <p>Los barrios seleccionados son:<span class="badge" id="barrios"></span></p>
  </div>
</div>
<div id="mapa"></div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <h3>Home</h3>
  <p>Validation type: <%= I18n.t('label.validation_status_'+@user.validation_status.to_s) %></p>
  <p><%= t('activerecord.attributes.user.name') %>: <%= @user.name %></p>
  <p><%= t('activerecord.attributes.user.last_name') %>: <%= @user.last_name %></p>
  <p><%= t('activerecord.attributes.user.birth_date') %>: <%= @user.birth_date %></p>
  <p><%= t('activerecord.attributes.user.address') %>: <%= @user.address %></p>
  <p><%= t('activerecord.attributes.user.mobile_phone') %>: <%= @user.mobile_phone %></p>
  <p><%= t('activerecord.attributes.user.profile_photo') %>: <%= image_tag @user.facebook_photo_url %></p>
  <p><%= t('activerecord.attributes.user.id_scan') %>: <%= image_tag(@user.id_scan.url) %></p>
<% else %>
  <div class="jumbotron">
    <h2>Welcome to delivery.com</h2>
    <p>Si ya sos usuario , en el menu podés ingresar. Sino registrate ahora! 
      <%= link_to "Sign up", new_registration_path('user') %><br />
    </p>
  </div>
<% end %>

<br>
<%= link_to "Español", "/?locale=es" %>
<%= link_to "English", "/?locale=en" %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="<%= root_path %>">Delivery test</a>
</div>


<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li><%= link_to t('menu.configure_delivery'), delivery_path %></li>
      <li><%= link_to t('menu.validate_your_data'), validate_your_data_users_path %></li>
    <% end %>
  </ul>

  <% unless user_signed_in? %>
    <%= form_for("user", :url => user_session_path, :html => {:class=>"navbar-form navbar-left"}) do |f| %>
      <div class="form-group">
        <%= f.text_field :email, :class => "form-control", :placeholder => t('label.user') %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, :class => "form-control", :placeholder => t('label.password') %>
      </div>
      <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-lock"></span>&nbsp;<%= t('buttons.login') %></button> 

      <%- User.omniauth_providers.each do |provider| %>
      <%= link_to t('.sign_in_with_provider', :provider => provider.to_s.titleize, :default => "Sign in with #{provider.to_s.titleize}"), omniauth_authorize_path('user', provider), :class => "btn btn-info" %><br />
      <% end -%>

    <% end %>
  <% end %>
    
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-cog"></span> Mi cuenta
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete do %>
              <span class="glyphicon glyphicon-off"></span> Salir
            <% end %>
          </li>
        </ul>
      </li>
    <% else %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Invitado <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Ingresar', new_user_session_path %></li>
          <li><%= link_to 'Registrarse', new_user_registration_path %></li>
        </ul>
      </li>
    <% end %>      
  </ul>
</div><!-- /.navbar-collapse -->
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Delivery" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Delivery" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# application layout styled for Twitter Bootstrap 3.0 %>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
         <div class="row">
           <div class="col-md-12">
             <%= render 'layouts/messages' %>
             <%= yield %>
           </div>
         </div>
      </div>
    </main>
  </body>
</html>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/users/validate_your_data.html.erb
<h1><%= t('menu.validate_your_data') %></h1>

<%= t('text.your_validation_level_is') %>
<label><%= t('label.validation_status_'+current_user.validation_status.to_s) %></label>

<div class="jumbotron">
  <% if current_user.validation_status == 1 %>
    <p><%= t('text.reach_next_validation_level') %></p>

    <% unless current_user.mobile_phone_code.blank? %>
      <small>Code: <%= current_user.mobile_phone_code %></small>

      <%= form_for(current_user, url: validate_mobile_phone_users_path, class: 'form-horizontal', role: 'form', method: 'post') do |f|  %>
        <%= t('text.complete_code') %>
        <br>
        <label><%= t('activerecord.attributes.user.mobile_phone_code') %></label>
        <%= text_field_tag :mobile_phone_code_received, nil, class: 'form-control' %>
        <%= f.submit t('button.validate_code'), class: 'btn btn-success' %>
      <% end %>
    <% else %>
      <%= form_for(current_user, url: send_sms_users_path, class: 'form-horizontal', role: 'form', method: 'post') do |f|  %>
        <%= t('text.will_send_sms') %>
        <br>
        <label><%= t('activerecord.attributes.user.mobile_phone') %></label>
        <%= f.telephone_field :mobile_phone, class: 'form-control' %>
        <%= f.submit t('button.send_sms'), class: 'btn btn-success' %>
      <% end %>
    <% end %>

  <% elsif current_user.validation_status == 2 %>
    <p><%= t('text.reach_next_validation_level') %></p>

    <%= form_for(current_user, url: validate_id_image_users_path, class: 'form-horizontal', role: 'form', method: 'post') do |f|  %>
      <%= t('text.validate_id_image') %>
      <br>
      <label><%= t('activerecord.attributes.user.id_scan') %></label>
      <%= f.file_field :id_scan %>
      <%= f.submit t('button.upload_id'), class: 'btn btn-success' %>
    <% end %>


  <% elsif current_user.validation_status == 3 %>
    <p><%= t('text.max_validalidation_level') %></p>
  <% end %>
</div>

<br>